### ISSUE TITLE
mongodb_replicaset - Allow to be provided as dictionaries

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/mongodb#37]
##### SUMMARY

````
- name: Ensure replicaset rs0 exists
  mongodb_replicaset:
    login_host: localhost
    login_user: admin
    login_password: admin
    replica_set: rs0
    members:
    - "mongodb1:27017":
          priority: 1
    - "mongodb2:27017":
          priority: 0
    - "mongodb3:27017":
          priority: 0
  when: groups.mongod.index(inventory_hostname) == 0
```

The members list of dictionaries would be transformed into the following...

```
members: [
    { "_id": 0, "host": "mongodb1:27017", "priority": 1 },
    { "_id": 1, "host": "mongodb2:27017", "priority": 0 },
    { "_id": 1, "host": "mongodb3:27017", "priority": 0 },
]
```

We could allow any keys in the dictionary to future-proof it. "_id" value should be positional.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

mongodb_replicaset

**Comment by rhysmeister** [comment]
Works better with the following dict format...

```
- name: Create a replicaset and use a custom priority for each member
  mongodb_replicaset:
    login_host: localhost
    login_user: admin
    login_password: admin
    replica_set: rs0
    members:
    - host: "localhost:3001":
      priority: 1
    - host: "localhost:3002":
      priority: 0.5
    - host: "localhost:3003":
      priority: 0.5
  when: groups.mongod.index(inventory_hostname) == 0
```
